# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cmdservice:
    image: cmdservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6969:6969
